name: Node.js Package
on:
  push:
    tags:
      - '*node[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: apply patch
      run: (cd deps/mbedtls; for P in ../../patches/*.patch ; do patch -r - -s -N -p1 < $P ; done)
      shell: bash

    # npmに公開する.npmrcファイルを設定する
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    # npmに公開する
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # GitHub パッケージに公開する .npmrc ファイルを設定する
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        # デフォルトはワークフローファイルを所有するユーザまたは Organization
        #scope: '@octocat'
    # GitHub パッケージに公開する
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

